### ISSUE TITLE
Redmine 3.4 Settings cannot be saved

### ISSUE THREAD

**Issue by Niremizov** [tleish/redmine_remote_revision_url#12]
/settings/plugin/redmine_remote_revision_url

Settings view fix for redmine 3.4 https://github.com/tleish/redmine_remote_revision_url/commit/e70a057e2b1f00f5586dc7c6da4e32912e44c0b0#diff-bef0abc2932848150bf1cca45f96061e

was overwritten by next commits. At that moment settings cannot be saved.

**Comment by tleish** [comment]
Similar fix was made before, but then it broke in 3.4.2.

see: https://github.com/Niremizov/redmine_remote_revision_url/commit/f6e9692ea3eea6a5262dddef3169af96d95ba58f#diff-bef0abc2932848150bf1cca45f96061e

I forget the details why this broke, but I think it might have partly do to with:

```ruby
settings[:open_in_new_window]
# vs
settings['open_in_new_window']
```

Before accepting this, this needs to be tested on 3.4.2

**Comment by tofi86** [comment]
The settings names are a mess at the moment. This also mixed up migration from an older plugin version. See #14

**Comment by cometjc** [comment]
Not using symbol to access setting let my 3.4.4 can read (and save) options. However strings and symbols should be identical after resolving symbols, i have no idea what's happening :confused: 

https://github.com/jcppkkk/redmine_remote_revision_url/commit/bbcacf2fead878e73f94f78c0c2440c6b0c83dc4

**Comment by tleish** [comment]
It seems some configurations are serialized as hash with string and others are as symbols.  Not sure why.  If we convert the hash to a hash with indifferent access, this would resolve the issue that this breaks some configurations and not others.

**Comment by tleish** [comment]
I no longer use Redmine and cannot effectively update and maintain this repo.  Let me know if interested in taking it over?
