### ISSUE TITLE
Migration fails, every remote revision setting lost!

### ISSUE THREAD

**Issue by tofi86** [tleish/redmine_remote_revision_url#14]
I updated from commit 478d418

```
# git fetch
remote: Counting objects: 45, done.
remote: Total 45 (delta 17), reused 17 (delta 17), pack-reused 28
Unpacking objects: 100% (45/45), done.
From https://github.com/tleish/redmine_remote_revision_url
   478d418..f0b6c33  master     -> origin/master
```

Had a look at the commit history and decided it's worth a try to update.

```
l# git pull
Updating 478d418..f0b6c33
Fast-forward
 README.md                                          |    5 +++-
 .../redmine_remote_revision_url/_settings.html.erb |    9 ++++----
 db/migrate/001_update_saved_settings.rb            |   18 +++++++++++++++
 init.rb                                            |    9 ++++++--
 .../application_helper_patch.rb                    |    8 ++-----
 .../repositories_helper_patch.rb                   |    2 +-
 .../repository_patch.rb                            |   24 +++++++++++++++-----
 7 files changed, 54 insertions(+), 21 deletions(-)
 create mode 100644 db/migrate/001_update_saved_settings.rb
```

Then I ran the migrations:

```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
(in /var/www/projekte/redmine-3.4)
...
Migrating redmine_remote_revision_url (Remote Revision URL)...
== 1 UpdateSavedSettings: migrating ===========================================
== 1 UpdateSavedSettings: migrated (0.0162s) ==================================

...
```

Looks good. Then I restarted Redmine.

And all plugin fields in all repositories are empty. Every Git remote is lost!

And I thought there had been proper migrations with #10 ?!

**Comment by tofi86** [comment]
When looking at the database tables I can still see all my settings in the field "extra_info". So it's obviously not completely lost...

How can I restore it?

**Comment by tofi86** [comment]
Forgot to tell about my environment:

```
Environment:
  Redmine version                3.4.5.stable.17303
  Ruby version                   2.2.1-p85 (2015-02-26) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  ...
  redmine_remote_revision_url    0.3.2
  ...
```

**Comment by tofi86** [comment]
Now I applied the changes from PR #13, but it didn't help.

Next:

> When looking at the database tables I can still see all my settings in the field "extra_info". So it's obviously not completely lost...

Info before I saved a new remote url:

```
extra_remote_revision_url: https://code.host.tld/group/project/commit/:revision
extra_remote_revision_text: GitLab
```

Then I saved the exact info again for this project and now I have duplicates:

```
extra_remote_revision_url: https://code.host.tld/group/project/commit/:revision
extra_remote_revision_text: GitLab
:extra_remote_revision_url: https://code.host.tld/group/project/commit/:revision
:extra_remote_revision_text: GitLab
```

I think #13 is incomplete because there are still other settings which are stored with a colon `:` in front which seems to be useless:
* https://github.com/tleish/redmine_remote_revision_url/blob/master/lib/redmine_remote_revision_url/repository_patch.rb#L6
* etc. in lines 12, 16, 20

**Comment by tofi86** [comment]
So I updated the 20 repositories in my DB manually and added a colon `:` before the extra_info field names. Works again.

However, I still think that this is a regression from previous bugfixes. None of the other `extra_info` fields are starting with a colon, it's just a plain string token.

**Comment by tleish** [comment]
I no longer use Redmine and cannot effectively update and maintain this repo.  Let me know if interested in taking it over?
