### ISSUE TITLE
Empty url for "associated revisions" if same repo is setting in multiple project with empty value in one of projects

### ISSUE THREAD

**Issue by cometjc** [tleish/redmine_remote_revision_url#3]
Good plugin !  :smiley: :+1: 

The remote url for "associated revisions" on issue page is empty.
![image](https://cloud.githubusercontent.com/assets/84070/8065144/22aa29f2-0f12-11e5-9bf7-e060f348c20a.png)

So if checked option "Replace the Redmine Revision Links", revision links will disappear.

**Comment by tleish** [comment]
Hm, not sure why this is happening without seeing the values saved with configuration.  Can you provide additional information?

**Comment by tleish** [comment]
Figured out what was happening.  You did not yet enter the URL for the remote repository as specified in the README section Repository Settings.

see: https://github.com/tleish/redmine_remote_revision_url#repository-settings

Note: I also updated the plugin to handle entries left blank.  When there is no URL, the plugin will not make any changes to the page.

**Comment by cometjc** [comment]
@tleish here is my setting, i did enter the URL for the remote repository, pulled new version source code. But url is still not showing on issue page.
Did i miss something?

![image](https://cloud.githubusercontent.com/assets/84070/8073693/f1d23592-0f5a-11e5-99a0-50f82bb6c108.png)

![image](https://cloud.githubusercontent.com/assets/84070/8073799/5edc2a2a-0f5c-11e5-82a3-0537fb2b9a11.png)
![image](https://cloud.githubusercontent.com/assets/84070/8073801/5fdf3bc4-0f5c-11e5-9f3f-caee794a4d22.png)

**Comment by tleish** [comment]
I just tested 2.6.5 didn't have any problems?  Take a look at your repositories table in the database.  Is there more than one entry for your git repo?

**Comment by cometjc** [comment]
@tleish your are correct, i do have same repo in two project since it's a common sub-module included by two project 
![image](https://cloud.githubusercontent.com/assets/84070/8075952/f80ab560-0f78-11e5-8ea3-64ea96285032.png)

**Comment by tleish** [comment]
Then you may have edited the URL for one, but not the other

**Comment by cometjc** [comment]
Nice! the url shows now!!

So can it be fixed? e.g. select repo by it's project id or other methods?

![image](https://cloud.githubusercontent.com/assets/84070/8075985/634209e6-0f79-11e5-9c5c-a6add2fe9c2d.png)

**Comment by tleish** [comment]
You have a good suggestion, however I think sometimes we try to get too smart with software.  If for some reason you want the URL to show in one project but not another, then being to smart with the code would not allow a user to disable it and only show it in the one repo.

Another scenario.  Let's also assume for a minute that there were 2 repository entries, and only one contained the Remote URL.  Then the Remote URL displayed for both repositories all over the site.  Then later, the repository with the URL was deleted and all of the sudden the Remote URL disappeared from all projects.  Unexpected behavior.

Redmine treats the repos completely separate in the database, even if they share the same path.  Each one has their own set of changes in the database, etc.  The current remote URL model follows the same pattern that Redmine has set.  Each repo entry has it's own copy of a remote URL.  If you want the remote URL to show up in both, simply enter it twice to again add that same URL to the same linked repo in another project.

Glad we solved the problem.  Enjoy!
