### ISSUE TITLE
State compatibility with Redmine 3.x/3.1

### ISSUE THREAD

**Issue by fbender** [tleish/redmine_remote_revision_url#4]
Would be nice to know if this plugins is compatible with Redmine 3.x (current release: 3.1) since support for 2.6 will end sometime after this december. 

The [plugin list entry](http://www.redmine.org/plugins/redmine_remote_revision_url) states that the released version has not been tested with anything newer than 2.6, however this repo contains commits that were created after the release date in the plugin list.

If this plugin is not compatible with Redmine 3.x, what's your roadmap/timeframe for supporting newer versions?

**Comment by tleish** [comment]
The plugin has simply never been tested on Redmine 3.x.  If someone wants to they can install and test it on 3.x and report back.  If they report back that it fails, I'd suggest they consider submitting a bug fix/patch.  When I have time I might consider looking into fixing it.

**Comment by tleish** [comment]
Just tested compatibility with Redmine 3.x, and works.  Updated plugin page.

**Comment by fbender** [comment]
Awesome, thanks for the info!

Just FYI, in the "Notes" section the text is not up to date yet: 

```
I have not tested this with anything above 2.x. If somebody else does and it works or there's an issue, I'd appreciate you letting me know.
```
